Updates

diff --git a/.config/lf/lfrc b/.config/lf/lfrc
--- a/.config/lf/lfrc
+++ b/.config/lf/lfrc
@@ -1,5 +1,5 @@
 # interpreter for shell commands (needs to be POSIX compatible)
-set shell sh
+set shell bash
 
 # set '-eu' options for shell commands
 # These options are used to have safer shell commands. Option '-e' is used to
@@ -25,6 +25,28 @@ set previewer ~/.config/lf/previewer
 set cleaner ~/.config/lf/cleaner
 set icons true
 set hiddenfiles ".*:*.aux:*.bbl:*.bcf:*.blg:*.run.xml:*.toc:*.fls:*.lof:*.lot:*.lgg:*.ltt:*.out:*.fdb_latexmk"
+#set ratios 1:3:4
+set info size:time
+#set drawbox
+
+# show a warning on startup if lf is running as a nested instance
+%[ $LF_LEVEL -eq 1 ] || echo "Warning: You're in a nested lf instance!"
+
+cmd on-cd &{{
+    # '&' commands run silently in background (which is what we want here),
+    # but are not connected to stdout.
+    # To make sure our escape sequence still reaches stdout we pipe it to /dev/tty
+    printf "\033]0; $(pwd) - lf\007" > /dev/tty
+}}
+
+# also run at startup
+on-cd
+
+cmd on-quit &{{
+        lf -remote 'quit'
+}}
+
+#on-quit
 
 map x quitcd
 cmd quitcd ${{
@@ -58,9 +80,9 @@ cmd open ${{
         text/csv|application/vnd.oasis.opendocument.spreadsheet|application/vnd.ms-excel|application/vnd.openxmlformats-officedocument.spreadsheetml.sheet) sc-im $f ;;
         text/html) setsid -f $BROWSER $f ;;
         text/*|application/octet-stream) $EDITOR $fx ;;
-        inode/symlink) $EDITOR $fx ;;
+        inode/symlink) $EDITOR $(readlink $fx) ;;
         image/svg+xml) display -- $f ;;
-        image/*) setsid -f xdg-open $f ;;
+        image/*) setsid -f nsxiv $f ;;
         audio/*) mpv --audio-display=no $f ;;
 	video/*) setsid -f mpv $f -quiet >/dev/null 2>&1 ;;
     esac
@@ -122,27 +144,92 @@ cmd zip ${{
     rm -rf $1
 }}
 
-cmd moveto ${{
-	clear; tput cup $(($(tput lines)/3)); tput bold
-	set -f
-	clear; echo "Move to where?"
-	dest="$(sed -e 's/\s*#.*//' -e '/^$/d' -e 's/^\S*\s*//' $XDG_CONFIG_HOME/lf/bm-dirs | fzf | sed 's|~|$HOME|')" &&
-	for x in $fx; do
-		eval mv -iv \"$x\" \"$dest\"
-	done &&
-	notify-send " File(s) moved to $dest."
+cmd paste_try_cow &{{
+    # # This was very helpful for debugging:
+    # log_file="$HOME/lf-reflink-log-$(date +'%Y-%m-%d_%H-%M-%S')"
+    # [ -f "$log_file" ] || touch "$log_file"
+    # exec 1>> $log_file 2>&1
+    # set -x
+
+    # In theory, this may fail,
+    # but I tested it on selection with 10k files - everything worked (bash)
+    set -- $(cat ~/.local/share/lf/files)
+    mode="$1"
+    shift
+
+    if [ $mode = 'copy' ]; then
+        # Reflink if all items of selection and the destination are on the
+        # same mount point and it is CoW fs.
+        # (to make sure reflink never fails in first place, so we don't have to
+        # clean up)
+
+        src_targets="$(df --output=target -- "$@" | sed '1d' | sort -u)"
+
+        if [ "$(df --output=target -- "$PWD" | tail -n 1)" = \
+             "$(echo "$src_targets" | tail -n 1)" ] && \
+             (( "$(echo "$src_targets" | wc -l)" == 1 )) && \
+             [[ "$(df --output=fstype -- "$PWD" | tail -n 1)" =~ ^(btrfs|xfs|zfs)$ ]]; then
+
+            echo 'selected copy and cp reflink paste'
+
+            start=$(date '+%s')
+
+            # Handle same names in dst
+            # TODO parallelism, idk - but exit/return/break won't stop the loop from subshell...
+            for i in "$@"; do
+                name="${i##*/}"
+                original="$name"
+
+                count=0
+                while [ -w "$PWD/$name" ]; do
+                    count=$((count+1))
+                    name="$original.~$count~"
+                done
+
+                set +e
+                cp_out="$(cp -rn --reflink=always -- "$i" "$PWD/$name" 2>&1)"
+                set -e
+
+                if [ ! -z "$cp_out" ]; then
+                    lf -remote "send $id echoerr $cp_out"
+                    exit 0
+                fi
+            done
+
+            finish=$(( $(date '+%s') - $start ))
+            t=''
+            if (( $finish > 2 )); then
+                t="${finish}s"
+            fi
+
+            # Or just skip a file when names are the same.
+            # (A LOT faster if you e.g. pasting selection of 10k files)
+            # cp -rn --reflink=always -- "$@" .
+
+            lf -remote "send clear"
+
+            green=$'\u001b[32m'
+            reset=$'\u001b[0m'
+            lf -remote "send $id echo ${green}reflinked!${reset} $t"
+        else
+            echo 'selected copy and lf native paste'
+            lf -remote "send $id paste"
+        fi
+
+    elif [ $mode = 'move' ]; then
+        echo 'selected move and lf native paste'
+        lf -remote "send $id paste"
+    fi
+
+    # # for debug
+    # set +x
+
+    lf -remote "send load"
 }}
 
-cmd copyto ${{
-	clear; tput cup $(($(tput lines)/3)); tput bold
-	set -f
-	clear; echo "Copy to where?"
-	dest="$(sed -e 's/\s*#.*//' -e '/^$/d' -e 's/^\S*\s*//' $XDG_CONFIG_HOME/lf/bm-dirs | fzf | sed 's|~|$HOME|')" &&
-	for x in $fx; do
-		eval cp -ivr \"$x\" \"$dest\"
-	done &&
-	notify-send " File(s) copies to $dest."
-}}
+# name is different to avoid recursive calls
+map p paste_try_cow
 
-map Y copyto
-map D moveto
+map V push :!vim<space>
+map W $setsid -f $TERMINAL >/dev/null 2>&1
+map Y $printf "%s" "$fx" | xclip -selection clipboard
